# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='block.proto',
  package='stordy.block',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x62lock.proto\x12\x0cstordy.block\"\x07\n\x05\x45mpty\"8\n\x11GetFullChainReply\x12#\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x13.stordy.block.Block\"\xdf\x01\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\r\x12\x15\n\rprevious_hash\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0c\n\x04hash\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x05 \x01(\r\x12\x12\n\npublic_key\x18\x06 \x01(\t\x12\x15\n\rblock_context\x18\x07 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x08 \x01(\t\x12#\n\x1bprevious_expired_block_hash\x18\t \x01(\t\x12 \n\x18previous_block_signature\x18\n \x01(\t\"&\n\x10\x46indBlockRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t\"#\n\rLengthRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t\"\x1d\n\x0bLengthReply\x12\x0e\n\x06length\x18\x01 \x01(\r2\x93\x03\n\x0c\x42lockService\x12\x36\n\x08\x41\x64\x64\x42lock\x12\x13.stordy.block.Block\x1a\x13.stordy.block.Empty\"\x00\x12\x42\n\tFindBlock\x12\x1e.stordy.block.FindBlockRequest\x1a\x13.stordy.block.Block\"\x00\x12G\n\x0bLengthBlock\x12\x1b.stordy.block.LengthRequest\x1a\x19.stordy.block.LengthReply\"\x00\x12:\n\x0cGetLastBlock\x12\x13.stordy.block.Empty\x1a\x13.stordy.block.Block\"\x00\x12:\n\x06Length\x12\x13.stordy.block.Empty\x1a\x19.stordy.block.LengthReply\"\x00\x12\x46\n\x0cGetFullChain\x12\x13.stordy.block.Empty\x1a\x1f.stordy.block.GetFullChainReply\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='stordy.block.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=36,
)


_GETFULLCHAINREPLY = _descriptor.Descriptor(
  name='GetFullChainReply',
  full_name='stordy.block.GetFullChainReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='stordy.block.GetFullChainReply.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=94,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='stordy.block.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='stordy.block.Block.index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_hash', full_name='stordy.block.Block.previous_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='stordy.block.Block.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='stordy.block.Block.hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='stordy.block.Block.nonce', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='stordy.block.Block.public_key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_context', full_name='stordy.block.Block.block_context', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='stordy.block.Block.device', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_expired_block_hash', full_name='stordy.block.Block.previous_expired_block_hash', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_block_signature', full_name='stordy.block.Block.previous_block_signature', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=320,
)


_FINDBLOCKREQUEST = _descriptor.Descriptor(
  name='FindBlockRequest',
  full_name='stordy.block.FindBlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='stordy.block.FindBlockRequest.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=360,
)


_LENGTHREQUEST = _descriptor.Descriptor(
  name='LengthRequest',
  full_name='stordy.block.LengthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='stordy.block.LengthRequest.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=397,
)


_LENGTHREPLY = _descriptor.Descriptor(
  name='LengthReply',
  full_name='stordy.block.LengthReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='stordy.block.LengthReply.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=428,
)

_GETFULLCHAINREPLY.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['GetFullChainReply'] = _GETFULLCHAINREPLY
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['FindBlockRequest'] = _FINDBLOCKREQUEST
DESCRIPTOR.message_types_by_name['LengthRequest'] = _LENGTHREQUEST
DESCRIPTOR.message_types_by_name['LengthReply'] = _LENGTHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.Empty)
  })
_sym_db.RegisterMessage(Empty)

GetFullChainReply = _reflection.GeneratedProtocolMessageType('GetFullChainReply', (_message.Message,), {
  'DESCRIPTOR' : _GETFULLCHAINREPLY,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.GetFullChainReply)
  })
_sym_db.RegisterMessage(GetFullChainReply)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.Block)
  })
_sym_db.RegisterMessage(Block)

FindBlockRequest = _reflection.GeneratedProtocolMessageType('FindBlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDBLOCKREQUEST,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.FindBlockRequest)
  })
_sym_db.RegisterMessage(FindBlockRequest)

LengthRequest = _reflection.GeneratedProtocolMessageType('LengthRequest', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHREQUEST,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.LengthRequest)
  })
_sym_db.RegisterMessage(LengthRequest)

LengthReply = _reflection.GeneratedProtocolMessageType('LengthReply', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHREPLY,
  '__module__' : 'block_pb2'
  # @@protoc_insertion_point(class_scope:stordy.block.LengthReply)
  })
_sym_db.RegisterMessage(LengthReply)



_BLOCKSERVICE = _descriptor.ServiceDescriptor(
  name='BlockService',
  full_name='stordy.block.BlockService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=431,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddBlock',
    full_name='stordy.block.BlockService.AddBlock',
    index=0,
    containing_service=None,
    input_type=_BLOCK,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindBlock',
    full_name='stordy.block.BlockService.FindBlock',
    index=1,
    containing_service=None,
    input_type=_FINDBLOCKREQUEST,
    output_type=_BLOCK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LengthBlock',
    full_name='stordy.block.BlockService.LengthBlock',
    index=2,
    containing_service=None,
    input_type=_LENGTHREQUEST,
    output_type=_LENGTHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLastBlock',
    full_name='stordy.block.BlockService.GetLastBlock',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_BLOCK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Length',
    full_name='stordy.block.BlockService.Length',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LENGTHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFullChain',
    full_name='stordy.block.BlockService.GetFullChain',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GETFULLCHAINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKSERVICE)

DESCRIPTOR.services_by_name['BlockService'] = _BLOCKSERVICE

# @@protoc_insertion_point(module_scope)
