FROM python:2.7-alpine

LABEL maintainer="CONSEG – Grupo de Confiabilidade e Segurança de Sistemas <conseg@pucrs.br>"
LABEL version="1.0"

WORKDIR /app

RUN apk update && \
    apk add gcc g++ make libffi-dev openssl-dev

COPY conf/pip.conf /etc/
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 9999

# python2.7 Gateway.py 50.16.193.245 9090 gateway-us-east-1 PoW &
# python2.7 Gateway.py 50.16.193.245 9090 gateway-us-west-2 PoW &
# python2.7 Gateway.py 50.16.193.245 9090 gateway-ap-northeast-1 PoW &
ENTRYPOINT  [ "python", "Gateway.py", "name-server", "9090", "gateway01", "PoW" ]
